### ISSUE TITLE
Qt Dictionaries 

### ISSUE THREAD

**Issue by Jihadist** [smurfomen/QSerializer#3]
What is the problem with Qt dictionaries types (QHash, QMap...)?

**Comment by smurfomen** [comment]
I cannot represent equivalent QMap elements in JSON. You can think of a QMap as a collection of objects with a key field and a value field. Close the issue if I answered your question.

**Comment by smurfomen** [comment]
dictionaries types is not supported now

You mean like this?
{
    "map": {
        "2" : 22,
        "3": 33
    }
}

**Comment by smurfomen** [comment]
> What is the problem with Qt dictionaries types (QHash, QMap...)?

i dropped 1.2 release. You may check dictionaries support)
